defaultNamespace: traefik

helm:
  repo: https://helm.traefik.io/traefik
  chart: traefik
  version: 37.2.0
  releaseName: traefik
  namespace: traefik
  valuesFiles:
    - values.yaml

kustomize:
  # To use a kustomization.yaml different from the one in the root folder
  dir: ""