apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: traefik
resources:
  - ns.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    # version: 37.2.0        # latest chart as of today
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
