apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
resources:
  - ns.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.16.1            # pick a current version for your env
    releaseName: cert-manager
    namespace: cert-manager
    valuesInline:
      installCRDs: true
      # Optional: tweak replica counts / affinity / resources here
      # replicaCount: 2
