apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - ../../apps/cert-manager
  - ../../apps/argocd

# optional common labels for everything in this cluster
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: platform
