apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.6/manifests/install.yaml
  - ingress-argocd.yaml

patches:
  - path: patches/argocd-server-svc.yaml
  - path: patches/argocd-cmd-params-cm.yaml
  - path: patches/argocd-secret.yaml
