apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./base/install.yaml
  - ./ingress-argocd.yaml

patchesStrategicMerge:
  - ./patches/argocd-server-svc.yaml
  - ./patches/argocd-cmd-params-cm.yaml
  - ./patches/argocd-secret.yaml
