apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
  commonName: argocd.lab
  dnsNames:
    - argocd.lab

  subject:
    organizations:
      - Cyber Armor SRL
    organizationalUnits:
      - Platform Security
    countries:
      - RO
    provinces:
      - Timis
    localities:
      - Timisoara
    postalCodes:
      - "300262"
    streetAddresses:
      - "Richard Waldemar Oschanitzky 3"
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
