bases:
- ../../base
patchesStrategicMerge:
# - argo-cd-cm.yaml
- argocd-cmd-params-cm.yaml
- argocd-server-service.yaml
- patch-priority-class.yaml


# ## proxmox lab
# patches:
# - path: overlays/proxmox/argo-cd-cm.yaml
# - path: overlays/proxmox/argocd-cmd-params-cm.yaml
# - path: overlays/proxmox/argocd-server-service.yaml
# - path: overlays/proxmox/patch-priority-class.yaml
#   target:
#     kind: Deployment
# - path: overlays/proxmox/patch-priority-class.yaml
#   target:
#     kind: StatefulSet

# # images:
# # - name: quay.io/argoproj/argocd
# #   newName: ghcr.io/argoproj/argo-cd/argocd
# #   newTag: 3.3.0-f26533ab
